name: 'Stale Bot'
on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Hey there! This issue has been inactive for 7 days. Are you still working on this? If not, please let us know so we can re-assign it to another contributor. If there is no activity in the next 3 days, it will be marked as stale.'
          stale-pr-message: 'This PR has been inactive for 7 days. Please update it or it will be closed soon.'
          days-before-stale: 7
          days-before-close: 3
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
